version: '3'

networks:
  connection:
    driver: bridge

services:
  node:
    build: .
    container_name: node
    ports:
    - "80:3000"
    - "443:443"
    volumes:
    - ./:/var/www
    links:
    - db
    networks:
    - connection